version: "3.8"

services:
  cv:
    build: .
    ports:
      - "8003:8003"
    env_file:
      - .env
    volumes:
      - ./models/weights:/app/models/weights
      - ./data/samples:/app/data/samples
